// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	Student student[N];

	makeStudent(student);
	printStudent(student);

	REQUIRE(student[0].id == 10001);
	REQUIRE(student[1].id == 10002);
	REQUIRE(student[2].id == 10003);
	REQUIRE(student[3].id == 10004);
	REQUIRE(student[4].id == 10005);
	REQUIRE(student[4].name == "July");
	REQUIRE(student[4].major == "Computer");

	cout << "--------------------------------------------------\n";
	cout << "--------------------------------------------------\n";
}